/**
 * Re-export all types from shared package.
 * Core package uses these types but doesn't define them.
 */
export type {
    Transaction,
    CategorizationResult,
    Rule,
    RuleSet,
    Account,
    ChartOfAccounts,
    JournalLine,
    JournalEntry,
    RunManifest,
    ParseResult,
    CategorizationOutput,
    PatternValidationResult,
    CollisionResult,
    PaymentPattern,
    Match,
    ReviewUpdate,
    MatchStats,
    MatchResult,
    MatchConfig,
    AccountInfo,
    JournalValidationResult,
    LedgerStats,
    LedgerResult,
} from '@finance-engine/shared';

export {
    TransactionSchema,
    CategorizationResultSchema,
    RuleSchema,
    RuleSetSchema,
    AccountSchema,
    ChartOfAccountsSchema,
    JournalLineSchema,
    JournalEntrySchema,
    RunManifestSchema,
    ParseResultSchema,
    CategorizationOutputSchema,
    PatternValidationResultSchema,
    CollisionResultSchema,
    PaymentPatternSchema,
    MatchSchema,
    ReviewUpdateSchema,
    MatchStatsSchema,
    MatchResultSchema,
    MatchConfigSchema,
    AccountInfoSchema,
    JournalValidationResultSchema,
    LedgerStatsSchema,
    LedgerResultSchema,
    UNCATEGORIZED_CATEGORY_ID,
    CONFIDENCE,
    PATTERN_VALIDATION,
    MATCHING_CONFIG,
    TXN_ID,
} from '@finance-engine/shared';
